# Generated by Django 3.0.5 on 2020-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_head', models.CharField(max_length=100)),
                ('budget_desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EarningMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_head', models.CharField(max_length=100)),
                ('expense_desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_head', models.CharField(max_length=100)),
                ('expense_desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
