# Generated by Django 3.0.5 on 2020-04-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finbalmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.FloatField()),
                ('budget_fy_startDate', models.DateField()),
                ('amount_used', models.FloatField()),
                ('amount_surplus', models.FloatField()),
                ('comments', models.TextField(max_length=500)),
                ('budget_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.BudgetMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.FloatField()),
                ('expense_date', models.DateField()),
                ('expense_invoice_no', models.CharField(blank=True, max_length=50)),
                ('expense_order_ref_no', models.CharField(blank=True, max_length=50)),
                ('expense_trn_ref_no', models.CharField(blank=True, max_length=50)),
                ('expense_comments', models.CharField(max_length=500)),
                ('budget_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.BudgetDetails')),
                ('expense_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.ExpenseMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EarningDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_amount', models.FloatField()),
                ('earning_date', models.DateField()),
                ('earning_invoice_no', models.CharField(blank=True, max_length=50)),
                ('earning_order_ref_no', models.CharField(blank=True, max_length=50)),
                ('earning_trn_ref_no', models.CharField(blank=True, max_length=50)),
                ('earning_comments', models.CharField(max_length=500)),
                ('budget_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.BudgetDetails')),
                ('earning_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finbalmanager.EarningMaster')),
            ],
        ),
    ]
