# Generated by Django 3.0.5 on 2020-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finbalmanager', '0002_budgetdetails_earningdetails_expensedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdetails',
            name='earning_tax_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='expense_tax_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='earningdetails',
            name='earning_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='expense_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
